import { copyFileSync, mkdirSync } from "node:fs";
import { defineConfig } from "rolldown";
import { dts } from "rolldown-plugin-dts";
import { createRollupLicensePlugin } from "rollup-license-plugin";
import { licensePluginOptions, PARTIAL_LIB_FILENAME } from "./scripts/third-party-licenses.mjs";

/**
 * Copy the hand-authored markdown artifacts (the public-API quickref,
 * the common-mistakes companion RECIPES.md, and the changelog) plus the
 * machine-readable contract IR (`baerly.spec.json`) into `dist/` so a
 * freshly-installed `node_modules/@gusto/baerly-storage/dist/API.md`
 * gives a CLI agent (no TS LS) the entire public surface in one read,
 * RECIPES.md gives a fast "why did my call fail" lookup keyed by exact
 * error string, and `baerly.spec.json` gives a tool/agent the
 * error-code/operator/method/route enumerations in one parseable read.
 * Named `API.md` — not `AGENTS.md` — to avoid colliding with the
 * scaffolded app's own `AGENTS.md` at the user's project root. The
 * `.d.ts` files are split into hash-suffixed shared chunks by the
 * bundler's type splitter; the quickref and recipe files are flat
 * siblings.
 */
const copyApiQuickref = () => ({
  name: "copy-api-quickref",
  closeBundle() {
    mkdirSync("dist", { recursive: true });
    copyFileSync("packages/server/API.md", "dist/API.md");
    copyFileSync("packages/server/RECIPES.md", "dist/RECIPES.md");
    // Ship the changelog too: a stranded agent that remembers an older
    // API reads `node_modules/@gusto/baerly-storage/dist/CHANGELOG.md`
    // to recover the current call. Maintained by Changesets at the repo
    // root; see docs/contributing/publishing.md.
    copyFileSync("CHANGELOG.md", "dist/CHANGELOG.md");
    // Ship the machine-readable contract IR so a freshly-installed
    // node_modules/@gusto/baerly-storage/dist/baerly.spec.json gives a
    // tool/agent the error-code/operator/method/route enumerations in
    // one parseable read. Generated by `pnpm gen:spec`; kept fresh by
    // the drift gate (`scripts/check-spec-drift.ts` in `pnpm verify`).
    copyFileSync("packages/server/spec/baerly.spec.json", "dist/baerly.spec.json");
  },
});

export default defineConfig({
  input: {
    index: "packages/server/src/index.ts",
    auth: "packages/server/src/auth/index.ts",
    http: "packages/server/src/http/index.ts",
    maintenance: "packages/server/src/maintenance.ts",
    observability: "packages/server/src/observability/index.ts",
    "app-config": "packages/protocol/src/app-config.ts",
    cloudflare: "packages/adapter-cloudflare/src/index.ts",
    node: "packages/adapter-node/src/index.ts",
    client: "packages/client/src/index.ts",
    "client-react": "packages/client/src/react/index.ts",
    dev: "packages/dev/src/index.ts",
    "dev-vite": "packages/dev/src/vite-plugin.ts",
  },
  // `fast-xml-parser` and `aws4fetch` are bundled into the library
  // entries that use them (`dist/node.js` + `dist/dev-vite.js`).
  // They used to be optional peer deps, but pnpm skips optional peers
  // on install, so a fresh `create-baerly-storage` scaffold's
  // `node_modules` had no copy on disk and `vite.config.ts` died on
  // first load with `Cannot find package '…'`. Bundling them in here
  // mirrors `packages/cli/rolldown.config.ts` (the bin) and trades some
  // cold-start bytes for a working scaffold. The `bundle-no-live-import`
  // test in `tests/integration/bundle-size.test.ts` pins this contract
  // across every entry.
  external: [
    /^node:/,
    "@cloudflare/workers-types",
    "@fast-check/vitest",
    "@vitest/expect",
    "react",
    "react-dom",
    "vite",
    "vitest",
  ],
  output: {
    dir: "dist",
    format: "esm",
    sourcemap: true,
    // Wipe `dist/` before each build. Stale files (e.g. an `AGENTS.md`
    // copy from before we renamed the quickref to `API.md`) would
    // otherwise survive incremental rebuilds and ship via the
    // package.json `files: ["dist"]` field.
    // ORDERING: this root build (with `cleanDir`) MUST run before the CLI
    // build in `pnpm build` — reordering would let `cleanDir` wipe the
    // CLI's already-written `.third-party-licenses.cli.json` partial.
    cleanDir: true,
  },
  // The license plugin discovers every third-party package bundled by
  // THESE library entries and writes a partial JSON manifest into
  // `dist/`. The CLI build writes its own partial; `pnpm build`'s final
  // step merges both into `dist/THIRD-PARTY-LICENSES.txt`. The plugin's
  // `unacceptableLicenseTest` fails the build on any non-permissive
  // (e.g. copyleft) bundled license. See scripts/third-party-licenses.mjs.
  plugins: [
    dts({ tsgo: true }),
    createRollupLicensePlugin(licensePluginOptions(PARTIAL_LIB_FILENAME)),
    copyApiQuickref(),
  ],
});
